# Generated by Django 2.2.6 on 2019-10-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('부장', '부장'), ('차장', '차장'), ('과장', '과장'), ('대리', '대리'), ('사원', '사원')], max_length=10, null=True),
        ),
    ]
