# Generated by Django 2.2.6 on 2019-10-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191003_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jobdesc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
