# Generated by Django 2.2.6 on 2019-10-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20191006_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='house_rules',
            new_name='house_rule',
        ),
    ]
